# Generated by Django 5.0.4 on 2024-05-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AniconnectAniDesc',
            fields=[
                ('anime_id', models.IntegerField(db_column='anime_id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('synopsis', models.TextField(blank=True, db_column='Synopsis', null=True)),
                ('image_url', models.TextField(blank=True, db_column='Image_Url', null=True)),
                ('genres', models.TextField(blank=True, db_column='Genres', null=True)),
            ],
            options={
                'db_table': 'aniconnect_ani_desc',
            },
        ),
    ]
