# Generated by Django 5.0.4 on 2024-05-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniconnect', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
