# Generated by Django 5.2.11 on 2026-02-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aniconnect', '0008_alter_userprofile_background_image_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendedAnime',
        ),
    ]
